### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by bamos** [Atcold/torch-TripletEmbedding#1]
Hi Alfredo, what's the licensing of this code?
If it's open/free and non-GPL, I'm interested in using
and contributing to the repository.
Can you add a LICENSE file?

-Brandon.

**Comment by Atcold** [comment]
Hey @bamos, yeah, it's open/free. What license would you suggest? MIT?
I have also a loading script which prepares the batches for training, but I'm not sure I can release that.

Edit: I will release the data loading package as well with a test file as soon as I've cleaned it!

**Comment by bamos** [comment]
I'm new to the Torch ecosystem, but many projects use a BSD 3-Clause license:
- https://github.com/torch/nn/blob/master/COPYRIGHT.txt
- https://github.com/torch/cunn/blob/master/LICENSE
- https://github.com/facebook/fbcunn/blob/master/LICENSE
- https://github.com/torch/torch7/blob/master/COPYRIGHT.txt

And sounds great about the data loading. Ping me when you've added it!

**Comment by Atcold** [comment]
Done, code is completely open (MIT) and you have a snippet for the triplets generation.
If you manage to make a LUA script to get the data set in the format the `data.lua` script asks for, it would be nice to push it in the `data` folder as well.

**Comment by bamos** [comment]
Hi @Atcold -

Thanks for the quick responses here. Getting the data into the right format and implementing the rest of facenet has been pretty nontrivial, but I have a model that's OK. I just released everything in a separate repo at:

https://github.com/cmusatyalab/openface

-Brandon.

**Comment by Atcold** [comment]
@bamos, truly impressive!
I will go though your `README.md` later, this afternoon, but I'm flattered to have contributed to this masterpiece in some way :grin: 
Keep up the good and open work!
