### ISSUE TITLE
Issue with gradient part

### ISSUE THREAD

**Issue by nitneh** [Atcold/torch-TripletEmbedding#6]
I think these piece of code: 

```lua
self.gradInput[1] = (n - p):cmul(self.Li:gt(0):repeatTensor(1,a:size(2)):type(a:type()) * 2/N)
self.gradInput[2] = (p - a):cmul(self.Li:gt(0):repeatTensor(1,a:size(2)):type(a:type()) * 2/N)
self.gradInput[3] = (a - n):cmul(self.Li:gt(0):repeatTensor(1,a:size(2)):type(a:type()) * 2/N)
```

should be:
(if we calculate loss gradient with respect to a,p,n), then this one will come)
```lua
self.gradInput[1] = (n - p):cmul(self.Li:gt(0):repeatTensor(1,a:size(2)):type(a:type()) * 2/N)
self.gradInput[2] = (- a):cmul(self.Li:gt(0):repeatTensor(1,a:size(2)):type(a:type()) * 2/N)
self.gradInput[3] = (a):cmul(self.Li:gt(0):repeatTensor(1,a:size(2)):type(a:type()) * 2/N)
```

Please correct me, if i am wrong..

**Comment by Atcold** [comment]
See [Wikipedia](https://en.wikipedia.org/wiki/Differentiation_rules#The_polynomial_or_elementary_power_rule).

**Comment by Atcold** [comment]
OK, just putting this here, for reference. But it's high school calculus...

![triplet](https://cloud.githubusercontent.com/assets/2119355/24809086/6a12ecba-1b8c-11e7-99d1-8d269bf18c04.jpg)

**Comment by nitneh** [comment]
yeah its a high school calculus, but its my badness that I have assume the normalization factor in triplet loss, and if we use normalization factor, then I think this simple high school calculus will become more easier :)

(a-p)T(a-p)= 2-2ap
(a-n)T(a-n)=2-2an

derivative of loss with respect to p=-2a
derivative of loss with respect to n= 2a

Thanks for high school calculus..

**Comment by Atcold** [comment]
What is `(a-p)T(a-p)= 2ap` supposed to mean? I am not following...

**Comment by nitneh** [comment]
its 2-2ap,
When the embeddings of the images are normalized to have unit l2 norm, the hinge loss function can be simplified to:
l(a, p,n) = max{0, g − 2ap+ 2an}

But, thanks for help...

I was looking for such special case, and confused with your generic case :)

**Comment by Atcold** [comment]
And what's `g`?

**Comment by Atcold** [comment]
Also (a-p)ᵀ(a-p) = a² + p² + 2aᵀp...

**Comment by Atcold** [comment]
Oh, I see now what you're taking about. Sure... 
I've implemented the triplet loss and its gradient. There is no assumption about the input embedding.

**Comment by nitneh** [comment]
Yeah thanks.. its my badness I confused it with normalised input embeedings :) a^2, p^2 will become 1 (unit normalized embeeding) .. Thanks a lot..
